server:
  port: 8090
spring:
  application:
    name: hello-app
    cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          instanceId: ${spring.application.name}:${random.value}
          healthCheckPath: /
          healthCheckInterval: 10s
